### ISSUE TITLE
Iphone opera mini

### ISSUE THREAD

**Issue by katz0018** [Sebby-T/animal-rescue-website#6]
Th logo and home are clashing.
I FREAKING LOVE YOU BANNER IMAGE, I would just add a little more hierarchy when it gets to iPhone size.

**Comment by Sebby-T** [comment]
Thanks! Yeah the phone size hierarchy seems a little lost, I'll see if I can bump it up a bit.

Thanks for the input! Loved your hairless cats website!

**Comment by katz0018** [comment]
Hehe thank you :)

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
