### ISSUE TITLE
Firefox text size increase issue

### ISSUE THREAD

**Issue by megan-smith-6** [Sebby-T/animal-rescue-website#9]
When the text size is increased the menu starts to pop out from the side of the screen. And it starts to overlap on top of the nav :/ 
Other than that, everything works really well!
<img width="321" alt="screen shot 2018-12-11 at 7 02 37 pm" src="https://user-images.githubusercontent.com/31959302/49838291-f9484a00-fd77-11e8-9261-e7534eda6c78.png">
<img width="306" alt="screen shot 2018-12-11 at 7 02 52 pm" src="https://user-images.githubusercontent.com/31959302/49838293-fc433a80-fd77-11e8-94db-0034513e23c4.png">

**Comment by Sebby-T** [comment]
The issue has been fixed! Thanks for the input
